"""Primary source judgments only; never supplies replacement app findings."""
from agent import stage02 as s, coverage_correction as c

# Each tuple is a primary judgment after reading complete cited body passages.
JUDGMENTS = {
81: {
'a0':(True,'Canonical resource API authentication body explicitly uses API keys managed in Dashboard.'),
'a1':(True,'Canonical resource auth body explicitly uses API-key username Basic without password.'),
'a2':(True,'Canonical resource auth body explicitly permits API key as Bearer for cross-origin requests.'),
'a3':(True,'Canonical API reference explicitly states REST, URL/body/response format and HTTP conventions.'),
'a4':(False,'POST /prices/:id and /products/:id update existing resources; they are not collection creation endpoints.'),
'a5':(True,'Canonical Prices/Products reference explicitly provides GET resource-id endpoints; narrow inspected read group.'),
'a6':(True,'Canonical Prices/Products reference explicitly provides POST resource-id endpoints for existing-resource updates.'),
'a7':(True,'Canonical Products reference explicitly provides DELETE resource-id endpoint.'),
'a8':(True,'Authentication body explicitly distinguishes unrestricted test secret keys and permission-restricted live keys.'),
'a9':(False,'Dashboard key management does not explicitly establish the full mandatory account/eligibility prerequisite inventory.'),
'a10':(True,'Resource auth body explicitly requires HTTPS and rejects plain HTTP and unauthenticated calls.'),
'a11':(False,'Provider/tools body does not contain the asserted mcp.stripe.com server URL; complete atom lacks cited support.'),
'a14':(False,'Another-user session role rule is explicit, but typically Administrator frequency assertion is unsupported.'),
'a15':(False,'Admin Dashboard configuration capability is not a mandatory MCP connection access gate.'),
'a16':(False,'Dashboard click/overflow-menu session management is misrepresented as MCP client/tool operations.'),
'a17':(True,'Native MCP body explicitly supports user-authorized actions and human confirmation for refunds/outbound payments.'),
'a18':(False,'Runtime human confirmation is not developer/public-app review; enum mismatch.'),
},
93: {
'a0':(True,'REST overview explicitly authenticates all resources with settings-generated API keys.'),
'a1':(True,'Official SDK authentication body explicitly configures bearerAuth/bearer_auth under Bearer Token Authentication.'),
'a2':(True,'Canonical API overview body explicitly classifies Fathom REST API.'),
'a3':(True,'Meeting-list quickstart and full response example explicitly include details, transcript, summary and action items; inspected group only.'),
'a4':(False,'User settings key creation is credential management, not resource API create capability.'),
'a5':(False,'Settings/key-user relationship does not explicitly establish the full account/registration eligibility prerequisite.'),
'a6':(True,'REST overview explicitly requires API-key resource authentication; retained credential prerequisite.'),
'a7':(True,'Vendor developer body explicitly says Fathom offers an official MCP server for meeting data.'),
'a8':(True,'Vendor setup body explicitly provides api.fathom.ai/mcp and directs compatible tools to authenticate.'),
},
72: {
'a0':(False,'Retirement date is explicit, but full migration recommendation is absent from this atom selected passages.'),
'a1':(False,'Legacy API-key blog body is stale; not_required state does not express retirement or current authentication.'),
'a2':(False,'Legacy Enterprise key caveat is not current personal authentication and not_required state mismatches its restrictions.'),
'a3':(False,'Obsolete API-key body is promoted with no current retirement limitation in the atom.'),
'a4':(False,'Legacy webhook lifetime is not an auth-mode fact.'),
'a5':(True,'Current PAT documentation explicitly recommends OAuth for third-party integrations.'),
'a6':(True,'Current Web API body explicitly supports OAuth token creation of bases on every named plan.'),
'a7':(False,'Service-account overview link summary is not body proof of an Enterprise API authentication mechanism.'),
'a8':(False,'PAT scope/resource text does not explicitly establish Bearer header authentication; PAT cannot be classified by inference.'),
'a9':(False,'PAT access/permissions assertion does not establish the selected Bearer mechanism label.'),
'a10':(False,'PAT lifetime is not an independently evidenced Bearer authentication mode.'),
'a11':(False,'PAT failure causes are not an auth-mode classification.'),
'a12':(False,'Organization-admin access is an alternative Enterprise path mislabeled personal auth.'),
'a13':(False,'Creator role/scope prerequisite is mislabeled Bearer auth instead of retained prerequisite atom.'),
'a14':(False,'PAT management UI actions do not establish Bearer resource authentication.'),
'a15':(False,'PAT scope/access selection is mislabeled Bearer auth.'),
'a16':(False,'Enterprise-only scopes are mislabeled personal auth and belong to a separate Enterprise path.'),
'a17':(False,'Enterprise server-side-only security requirement does not establish no authentication.'),
'a20':(True,'Current Web API record/schema/base route body supports this bounded inspected read group.'),
'a21':(True,'Current create-base endpoint plus product API guide explicitly support creating bases and records.'),
'a22':(True,'API guide explicitly supports record/base-entry updates; current token body bounds user permissions.'),
'a23':(False,'Deletion is explicit, but selected passage does not evidence the additional scopes/permissions assertions.'),
'a24':(True,'Enterprise body explicitly supports user/permission/share-link/audit management and Enterprise admin limitations; separate Enterprise atom.'),
'a25':(False,'Selected account/workspace description does not explicitly establish the mandatory account prerequisite for every personal API path.'),
'a26':(False,'Enterprise scopes are explicitly unavailable on Business plans; stale key caveat and commercial tiers are mixed into personal prerequisites.'),
'a27':(True,'Current PAT body explicitly bounds actions to user permissions and names Creator role/schema.bases:write for field creation.'),
'a28':(False,'Most Enterprise methods requiring admin does not establish all specifically named methods in this atom.'),
'a29':(True,'Vendor developer body and our-MCP-server heading explicitly identify Airtable MCP structure context and provider.'),
'a30':(True,'Vendor agents body explicitly advertises MCP-compatible read/write/query subject to existing permissions.'),
'purpose':(True,'True product body explicitly describes AI-native apps, workflow automation and embedded agents at Enterprise scale; concise product purpose.'),
},
61: {
'a0':(False,'PAT/built-in/app access tokens are mislabeled as API keys; resource mechanism is token Authorization.'),
'a1':(False,'PAT identity/permission assertion is not API-key authentication.'),
'a2':(False,'Fine-grained PAT permissions are mislabeled as API-key auth rather than a prerequisite atom.'),
'a3':(False,'Classic PAT scopes are mislabeled as API-key auth rather than prerequisites.'),
'a4':(False,'Conditional SAML authorization prerequisite is mislabeled API-key auth and not a separately identified organization path.'),
'a5':(False,'SSO failure behavior is not API-key authentication; selected multiple-organization body also does not assert the claimed 404/403 outcome.'),
'a6':(False,'SSO failure behavior is a conditional token prerequisite, not API-key authentication.'),
'a7':(False,'App-token SAML authorization is not API-key authentication.'),
'a8':(False,'GitHub App endpoint permissions are not API-key authentication.'),
'a9':(False,'App-client Basic evidence lacks a named primary resource endpoint and cannot establish data-resource Basic instead of app/token administration.'),
'a10':(False,'Client credentials creating access tokens belong to app/token administration, not primary resource Basic.'),
'a11':(False,'Finding client credentials on settings page is not primary resource Basic.'),
'a12':(False,'UI navigation to app settings does not establish resource authentication.'),
'a13':(True,'Canonical resource-auth body explicitly supports Authorization Bearer/token and JWT Bearer requirement.'),
'a14':(True,'Canonical resource API curl example explicitly uses Bearer Authorization.'),
'a15':(False,'Workflow-specific recommendation is assessed personal required and lacks explicit separation of its alternative credential path.'),
'a16':(False,'GitHub Actions credential path is not explicitly separated from assessed personal integration path.'),
'a17':(False,'Unsupported username/password does not establish no authentication; canonical none label contradicts the evidence.'),
'a18':(True,'Personal API access body explicitly allows creating fine-grained/classic PATs.'),
'a19':(True,'App API access body explicitly permits OAuth tokens and recommends GitHub Apps for permission control.'),
'a20':(True,'App client-credential body explicitly supports app operations including creating access tokens; retained only as credential path fact.'),
'a21':(False,'Keeping credentials secure is not evidence of credential creation eligibility.'),
'a22':(False,'Authentication rate-limit benefits do not establish any paid-plan gate.'),
'a23':(False,'REST/versioning are explicit but complete atom adds OpenAPI description absent from all selected passages.'),
'a24':(True,'Explicit MCP implementation in github/github-mcp-server vendor namespace, read/code/issues/PR/workflow body and hosted-server context establish provider.'),
'a25':(True,'Vendor repository body explicitly identifies GitHub-hosted remote and alternative local server.'),
'a26':(False,'Selected body describes optional PAT alternative, not mandatory account plus PAT requirement for every MCP path.'),
'a27':(True,'Repository body explicitly requires host GitHub/OAuth App configuration for the conditional remote OAuth path.'),
'a28':(False,'PAT is an alternative to OAuth, not universally required for MCP authentication.'),
'a30':(False,'Docker installation/image availability is mislabeled credential creation.'),
'a31':(False,'Building from source and setting PAT is mislabeled credential creation eligibility.'),
'a32':(True,'Repository body explicitly documents host-specific local configuration syntax and stability limitations.'),
},
55: {
'a0':(False,'Explicit REST body is valid, but atom is assessed as product rather than a resource API surface; no manual relabeling allowed.'),
'a3':(False,'Account requirement is from MCP setup and is assessed as product, not a separated API/MCP setup path.'),
'a4':(False,'Resource read body is valid but assessed product mode does not identify the resource API surface.'),
'a5':(False,'Selected body does not evidence schedule creation; product mode also mismatches resource API surface.'),
'a6':(False,'Key-value CRUD passage does not establish task update; product mode also mismatches resource API surface.'),
'a7':(False,'Valid key-value/request-queue deletion body is assessed product rather than resource API mode.'),
'a8':(False,'Valid Actor/task execution body is assessed product rather than resource API mode.'),
'a9':(False,'Scoped-token capability is assessed product and required despite scoped tokens being an optional alternative to unscoped tokens.'),
'a10':(False,'Scoped-token permissions are not separated as an alternative token path and atom is assessed product.'),
'a11':(False,'Selected body locates tokens but does not require token registration; product mode also mismatches resource setup.'),
'a17':(False,'MCP usage monitoring is not a paid-plan credential eligibility gate; wrong product surface.'),
'a18':(False,'MCP configuration is assessed product instead of a separated MCP surface.'),
'a19':(False,'Alternative agentic-payment resource and MCP credential paths are merged and assessed product.'),
'a20':(False,'Compatible MCP clients are not public app review; both label and surface mismatch.'),
'a22':(False,'User consent on MCP OAuth login is not partner approval; label and surface mismatch.'),
'a23':(False,'Organization token administrative path is assessed product and combines visibility permissions with broad optional gate classification.'),
},
42: {
'a1':(True,'Canonical authentication docs explicitly support Basic over HTTPS using consumer key/secret.'),
'a2':(False,'Fact and source specify OAuth 1.0a, but canonical label is oauth2; enum mismatch.'),
'a3':(True,'Canonical WordPress/WooCommerce REST reference explicitly supports REST, JSON and standard verbs.'),
'a8':(True,'Developer body explicitly ties key creation and lifecycle to a specific WordPress user.'),
'a9':(True,'Primary REST requirements explicitly require pretty non-Plain permalinks.'),
'a10':(False,'Free-core support disclaimer does not establish an explicit not-required commercial credential gate.'),
'a11':(True,'Native developer body explicitly states WooCommerce includes MCP support and AI store operations.'),
'a12':(False,'Native adapter and w7s extension are merged; selected body does not independently prove complete vendor ownership claim.'),
'a13':(False,'Deprecated native endpoint and w7s plugin activation path are merged without a separately identified plugin surface.'),
'a14':(False,'Deprecation is explicit but selected passage does not establish the claimed shared-adapter replacement instruction.'),
'a16':(False,'w7s plugin key-management path is not separated from native WooCommerce MCP.'),
'a17':(False,'manage_woocommerce requirement belongs to the w7s plugin path; merged native MCP prerequisite lacks surface separation.'),
'a18':(False,'w7s plugin read operations are not separated from native MCP resource scope.'),
'a19':(False,'Selected plugin passage states write key needed for changes, not the complete create operation assertion; plugin surface also merged.'),
'a20':(False,'Selected plugin passage does not explicitly establish update operations; plugin surface also merged.'),
'a21':(False,'Selected plugin passage does not explicitly establish deletion operations; plugin surface also merged.'),
'a22':(False,'No payment language in selected passage; not-required paid gate inferred from silence.'),
'a23':(False,'Plugin manage_woocommerce role requirement is merged into undifferentiated native MCP access.'),
'a24':(True,'Native remote-MCP troubleshooting body explicitly requires HTTPS and non-Plain permalinks.'),
'a25':(False,'w7s header/connector credential path is not explicitly separated from native MCP adapter path.'),
'a26':(True,'Native developer body explicitly deprecates WooCommerce-specific MCP endpoint and prohibits new integrations on it.'),
},
35: {
'a0':(True,'Connecting-to-API body explicitly supports own-account API-key authentication.'),
'a1':(True,'Body explicitly permits OAuth access tokens for API requests and recommends them for other-user account access.'),
'a2':(True,'Integration authentication body explicitly requires OAuth 2 for the Marketplace partner program.'),
'a3':(True,'API authentication body and resource request example support Basic with API key.'),
'a4':(True,'Body permits Bearer authentication with the documented OAuth/API credential choices.'),
'a5':(True,'Basics body explicitly requires a Mailchimp account.'),
'a6':(True,'Basics body explicitly conditions API capabilities on account plan level; does not assert a payment gate.'),
'a7':(True,'Developer methods reference explicitly states REST conventions and all named HTTP methods.'),
'a8':(True,'Canonical API methods body explicitly documents GET data retrieval; retained as a narrow action group.'),
'a9':(True,'Canonical methods body explicitly documents POST resource creation.'),
'a10':(True,'Canonical methods body explicitly documents PATCH/PUT resource updates.'),
'a11':(True,'Canonical methods body explicitly documents DELETE resource removal.'),
'a12':(True,'User API access body explicitly ties credentials to the creating/authorizing user and revokes them on removal.'),
'a13':(True,'User API access body explicitly documents role restrictions and 403 outcomes.'),
'a17':(True,'Partner-program application body explicitly requires applying and meeting requirements; distinct public-program path.'),
'a18':(True,'Partner-program body explicitly requires review/testing before joining; approval is scoped to that program.'),
'a19':(True,'Partner-program body explicitly describes review/testing to verify requirements and working integration.'),
'a20':(False,'Selected review passage does not itself establish the complete Marketplace-listing assertion.'),
'a21':(False,'OAuth authentication requirement is mislabeled as a scopes prerequisite; no scopes listed in the selected passage.'),
'a22':(False,'Required functionality features are not user/API permissions; canonical enum mismatch.'),
'a23':(False,'Plan-dependent capabilities do not evidence a required paid plan for obtaining credentials.'),
},
33: {
'a0':(True,'Current Marketing API member-permission body explicitly includes 3-legged OAuth consent for the Advertising API surface.'),
'a1':(False,'Developer/API-product approval is conflated with partner approval and combines other product access paths.'),
'a2':(False,'Audience Insights and Media Planning are adjacent APIs, not primary Advertising API access requirements.'),
'a3':(False,'Company Intelligence private API status belongs to an adjacent API.'),
'a4':(False,'Roles are permissions, not an account prerequisite; enum label mismatches the valid underlying body fact.'),
'a5':(True,'Getting-started body explicitly requires member-granted scopes and consent to all requested permissions.'),
'a6':(True,'Advertising permission table explicitly supports ad-account/report reading and applicable member roles.'),
'a7':(True,'Advertising overview explicitly provides creation/management of ad accounts, campaigns, creatives and campaign entities.'),
'a8':(False,'Manage permissions and overview do not explicitly establish the named update action groups.'),
'a9':(False,'Scope table does not establish deleting advertising entities; its delete language belongs to Community Management.'),
'a10':(True,'Advertising overview and Ad Account Users body explicitly support campaign entities and user-role management.'),
'a11':(False,'Development/Standard API access tiers are not an account plan or payment prerequisite.'),
'a12':(True,'Only configured Ad Accounts-tab accounts can be managed through the API; explicit configuration prerequisite.'),
'a13':(False,'Token Generator/Postman are documented testing utilities, not mandatory exclusive credential-generation paths.'),
'purpose':(False,'Sentence describes Marketing Platform API capabilities rather than the assigned advertising product purpose; plural APIs bypassed the old singular API guard.'),
},
11: {
'a0':(True,'Security body explicitly supports OAuth access tokens for API requests.'),
'a1':(True,'Global OAuth requirement and prohibition on ordinary customer tokens are explicit for multiple-customer apps.'),
'a2':(False,'The API token is a password used with Basic authentication; API-key mode misclassifies that mechanism even with deprecated status.'),
'a3':(True,'Basic API-token mechanism and migration warning are explicit; deprecated atom stays excluded from current auth display.'),
'a4':(False,'Client-side support is explicit, but security/future-compatibility recommendation is absent from the selected passages.'),
'a5':(False,'Selected benefits establish expiry and scopes but not the complete refresh-token assertion.'),
'a6':(True,'OAuth guide explicitly distinguishes authorization-code user-facing and client-credentials server flows.'),
'a7':(True,'Selected setup body explicitly covers code exchange, API usage, access/refresh tokens and refresh behavior.'),
'a8':(True,'Selected resource API usage and client-credentials sections establish inherited user permissions, no refresh token and re-requesting tokens.'),
'a10':(False,'Selected passages evidence users and ticket search, not the asserted articles resource group.'),
'a11':(False,'Generic POST action does not evidence creating the named organizations/tickets resources in these selected passages.'),
'a12':(False,'Batch-update limits are explicit, but PUT/PATCH mechanism is absent from cited body.'),
'a13':(False,'Deleting tokens in the Admin Center is UI management, not resource API deletion.'),
'a14':(True,'Security section explicitly requires a verified user; fragment is context-bounded to the Zendesk API reference.'),
'a15':(True,'OAuth setup explicitly requires client configuration and registered matching redirect URI.'),
'a16':(True,'API authentication body supports OAuth access tokens and explicitly identifies deprecated API tokens.'),
'a17':(True,'OAuth guide explicitly supports fine-grained scope restrictions.'),
'a18':(True,'OAuth guide explicitly bounds token access by authorizing user permissions.'),
'a23':(False,'Enterprise help-center theme feature is an alternative feature path, not a primary personal API prerequisite.'),
'a24':(True,'SSL requirements explicitly require TLS 1.2 and SNI and document retired TLS versions.'),
'purpose':(True,'True product FAQ body directly supports AI-first customer/employee service purpose and channels.'),
},
26: {
'a0':(False,'Authorization/install-flow parameters are not resource authentication; state is also treated as mandatory without selected support.'),
'a1':(False,'Scope inventory is not an independently evidenced resource-auth mode; partner/approval paths are not separated.'),
'a2':(False,'Token exchange and refresh are mislabeled as personal resource authentication.'),
'a3':(False,'Token revocation authentication belongs to token-exchange surface, not resource API authentication.'),
'a4':(False,'Bot installation authorization is not resource API authentication.'),
'a5':(False,'Advanced bot install flow belongs to an alternative install path, not mandatory personal resource authentication.'),
'a6':(False,'HTTP Basic is explicitly OAuth endpoint client authentication, not resource Basic.'),
'a8':(True,'Canonical developer reference explicitly specifies OAuth2 bearer-token resource authentication and Authorization header.'),
'a9':(False,'Selected 2020 terms do not state required developer account/application registration or current client-credential setup.'),
'a10':(False,'Selected historical 2020 terms do not establish current applicable registration requirements; current terms path was not closed.'),
'a11':(False,'Historical credentials text does not support the complete assigned-client-id/token/solely-registered-app requirement.'),
'a12':(True,'Current scope table plus Get Current User body explicitly show resource scopes and restricted/partner-only scopes.'),
'a13':(False,'Selected endpoint passages evidence channel permissions but not the additional claimed guild-member permission prerequisite.'),
'a14':(False,'Selected body evidences users/guilds/messages, not connections and the unspecified other-resource group.'),
'a15':(False,'Create Reaction passage does not establish creating messages or other resources.'),
'a16':(False,'User settings/role connection endpoints do not establish the additional commands update group.'),
'a17':(True,'Delete Current User Application Role Connection explicitly requires role_connections.write OAuth scope.'),
'a22':(False,'Selected historical terms passage is marketing-license prose, not application-review requirements.'),
'purpose':(True,'Official About Discord body directly supports concise gaming communications purpose.'),
},
3: {
'a0':(True,'Authentication heading bounds the x-api-token requirement to the personal token integration.'),
'a1':(True,'Selected body explicitly describes OAuth 2.0 authentication for apps and its implementation guide.'),
'a2':(True,'Canonical API reference explicitly states RESTful, JSON output and CORS support.'),
'a3':(False,'Cited example reads deals; sales pipeline resource retrieval is not independently established.'),
'a4':(False,'Create-lead and assign-task prose does not establish creating new tasks.'),
'a5':(False,'Nova product updates and a data-lake integration testimonial do not evidence API update actions.'),
'a6':(False,'Core-functionality statement does not explicitly evidence resource deletion.'),
'a7':(False,'Lead assignment product feature and generic workflows do not establish the named API execution scope.'),
'a9':(True,'Reference states API token can be obtained manually from Pipedrive app and authentication body requires it.'),
'a10':(False,'API included in plans and trial CTA do not establish an unrestricted not-required payment gate for credential eligibility.'),
'a11':(False,'Recommended sandbox account is not an evidenced mandatory account prerequisite for this path.'),
'a12':(False,'Public/unlisted/private app descriptions do not state registration requirements.'),
'a13':(True,'Security body explicitly requires API key or OAuth access token.'),
'a14':(False,'Selected body does not state scope requirements.'),
'a15':(False,'Product collaboration permissions do not establish API permissions prerequisites.'),
'a16':(False,'Plan-included API statement does not evidence advanced feature or integration plan restrictions.'),
'purpose':(True,'Product body explicitly covers small-business sales CRM, leads, activities, automation and closing deals; concise true purpose.'),
},
}

def main():
    directory=s.ROOT/'data/correction/body-pilot-v3-20260917'; out=[]
    for path in sorted((directory/'apps').glob('*.json')):
        v=s.read(path)
        promoted=[a for a in v.get('atoms',[]) if a['retained']]
        keys=[a['atom_id'] for a in promoted]
        if c.known(v.get('findings',{}).get('description','unknown')): keys.append('purpose')
        assert set(JUDGMENTS.get(v['id'],{}))==set(keys),(v['id'],keys)
        for key in keys:
            keep,reason=JUDGMENTS[v['id']][key]
            atom=next((a for a in promoted if a['atom_id']==key),None)
            out.append({'id':v['id'],'atom_id':key,'decision':'retain' if keep else 'downgrade','reason':reason,'passage_ids':atom['passage_ids'] if atom else v['purpose']['passage_ids'],'reviewer':'primary_agent_source_review','human_checked':False})
    s.save(directory/'primary-decisions.json',out,exclusive=True)
    print('Primary judgments:',len(out))

if __name__=='__main__': main()
